package modules

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
)

// generateBIOSReport gathers BIOS/UEFI version information and saves it to a text file.
func GenerateBIOSReport(outputDir string) error {
	var output bytes.Buffer
	outputPath := filepath.Join(outputDir, "BIOS_Report.txt")

	output.WriteString("BIOS/UEFI Version Information:\n")
	biosInfo, err := exec.Command("wmic", "bios", "get", "Manufacturer,SMBIOSBIOSVersion,ReleaseDate").Output()
	if err != nil {
		output.WriteString("Error gathering BIOS information.\n")
	} else {
		output.Write(biosInfo)
	}

	// Append footer
	output.WriteString("\n\nReport generated by GoDiag. Learn more at https://github.com/LewdLillyVT/godiag")

	// Save to file
	return os.WriteFile(outputPath, output.Bytes(), 0644)
}
