package modules

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
)

// dumpEventLogs extracts the last 10 warnings, errors, and critical errors from the event logs.
func DumpEventLogs(outputDir string) error {
	var output bytes.Buffer
	outputPath := filepath.Join(outputDir, "Event_Log_Dump.txt")

	// Gather last 10 warnings
	output.WriteString("Last 10 Warning Events:\n")
	warnings, err := exec.Command("wevtutil", "qe", "System", "/q:*[System[(Level=3)]]", "/c:10", "/f:text").Output()
	if err != nil {
		output.WriteString("Error gathering warning events.\n")
	} else {
		output.Write(warnings)
	}

	// Gather last 10 errors
	output.WriteString("\nLast 10 Error Events:\n")
	errors, err := exec.Command("wevtutil", "qe", "System", "/q:*[System[(Level=2)]]", "/c:10", "/f:text").Output()
	if err != nil {
		output.WriteString("Error gathering error events.\n")
	} else {
		output.Write(errors)
	}

	// Gather last 10 critical errors
	output.WriteString("\nLast 10 Critical Events:\n")
	criticals, err := exec.Command("wevtutil", "qe", "System", "/q:*[System[(Level=1)]]", "/c:10", "/f:text").Output()
	if err != nil {
		output.WriteString("Error gathering critical events.\n")
	} else {
		output.Write(criticals)
	}

	// Append footer
	output.WriteString("\n\nReport generated by GoDiag. Learn more at https://github.com/LewdLillyVT/godiag")

	// Save to file
	return os.WriteFile(outputPath, output.Bytes(), 0644)
}
