package modules

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
)

// generateHealthAndUsageReport gathers detailed health information of drives.
func GenerateHealthAndUsageReport(outputDir string) error {
	var output bytes.Buffer
	outputPath := filepath.Join(outputDir, "Health_Report.txt")

	// Collect Drive Health Information
	output.WriteString("Drive Health Information:\n")

	// Retrieve detailed drive information including model, serial number, size, and status
	driveInfo, err := exec.Command("wmic", "diskdrive", "get", "Model,SerialNumber,Size,Status").Output()
	if err != nil {
		output.WriteString("Error gathering drive health information.\n")
	} else {
		output.Write(driveInfo)
	}

	// Collect SMART data if available for each drive
	output.WriteString("\nSMART Data for Drives:\n")
	smartData, err := exec.Command("wmic", "diskdrive", "get", "Status,LastErrorCode,Capabilities,CapabilityDescriptions").Output()
	if err != nil {
		output.WriteString("Error gathering SMART data.\n")
	} else {
		output.Write(smartData)
	}

	// Append footer
	output.WriteString("\n\nReport generated by GoDiag. Learn more at https://github.com/LewdLillyVT/godiag")

	// Save to file
	return os.WriteFile(outputPath, output.Bytes(), 0644)
}
