package modules

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
)

// generateSecurityAndAntivirusLogs extracts recent security and antivirus-related events.
func GenerateSecurityAndAntivirusLogs(outputDir string) error {
	// Ensure the application has administrative privileges
	if err := ensureAdminPrivileges(); err != nil {
		return err
	}

	var output bytes.Buffer
	outputPath := filepath.Join(outputDir, "Security_Antivirus_Logs.txt")

	// Gather Security logs
	output.WriteString("Security Logs:\n")
	securityLogs, err := exec.Command("wevtutil", "qe", "Security", "/c:50", "/f:text").Output()
	if err != nil {
		output.WriteString("Error gathering security logs.\n")
	} else {
		output.Write(securityLogs)
	}

	// Gather Antivirus logs (specific to Windows Defender)
	output.WriteString("\nWindows Defender Logs:\n")
	antivirusLogs, err := exec.Command("powershell", "Get-MpThreatDetection").Output()
	if err != nil {
		output.WriteString("Error gathering antivirus logs.\n")
	} else {
		output.Write(antivirusLogs)
	}

	// Append footer
	output.WriteString("\n\nReport generated by GoDiag. Learn more at https://github.com/LewdLillyVT/godiag")

	// Save to file
	return os.WriteFile(outputPath, output.Bytes(), 0644)
}
