package modules

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
)

// generateQuickSysInfo gathers basic system information like CPU, GPU, RAM, and saves it to a text file.
func GenerateQuickSysInfo(outputDir string) error {
	var output bytes.Buffer
	outputPath := filepath.Join(outputDir, "Quick_System_Info.txt")

	// Collect CPU information
	output.WriteString("CPU Information:\n")
	cpuInfo, err := exec.Command("wmic", "cpu", "get", "Name,MaxClockSpeed,Manufacturer").Output()
	if err != nil {
		output.WriteString("Error gathering CPU information.\n")
	} else {
		output.Write(cpuInfo)
	}

	// Collect GPU information
	output.WriteString("\nGPU Information:\n")
	gpuInfo, err := exec.Command("wmic", "path", "win32_videocontroller", "get", "name,driverversion").Output()
	if err != nil {
		output.WriteString("Error gathering GPU information.\n")
	} else {
		output.Write(gpuInfo)
	}

	// Collect RAM information
	output.WriteString("\nRAM Information:\n")
	ramInfo, err := exec.Command("wmic", "memorychip", "get", "capacity,manufacturer,partnumber,speed").Output()
	if err != nil {
		output.WriteString("Error gathering RAM information.\n")
	} else {
		output.Write(ramInfo)
	}

	// Collect Motherboard and BIOS information
	output.WriteString("\nMotherboard and BIOS Information:\n")
	moboInfo, err := exec.Command("wmic", "baseboard", "get", "product,manufacturer").Output()
	if err != nil {
		output.WriteString("Error gathering Motherboard information.\n")
	} else {
		output.Write(moboInfo)
	}
	biosInfo, err := exec.Command("wmic", "bios", "get", "version,serialnumber").Output()
	if err != nil {
		output.WriteString("Error gathering BIOS information.\n")
	} else {
		output.Write(biosInfo)
	}

	// Additional system details if on Windows
	if runtime.GOOS == "windows" {
		output.WriteString("\nOS Information:\n")
		osInfo, err := exec.Command("systeminfo").Output()
		if err != nil {
			output.WriteString("Error gathering OS information.\n")
		} else {
			output.Write(osInfo)
		}
	}

	// Append footer
	output.WriteString("\n\nReport generated by GoDiag. Learn more at https://github.com/LewdLillyVT/godiag")

	// Save to file
	return os.WriteFile(outputPath, output.Bytes(), 0644)
}
